# Generated by Django 5.2.6 on 2025-09-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity_in_stock', models.IntegerField(default=0)),
            ],
        ),
    ]
